local opt = vim.opt

opt.tabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.smartindent = true
opt.number = true
opt.relativenumber = true
opt.cursorline = true
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.signcolumn = "yes"
opt.ignorecase = true
opt.smartcase = true
opt.hlsearch = false
opt.splitright = true
opt.splitbelow = true
opt.wrap = false
opt.termguicolors = true
opt.undofile = true
opt.updatetime = 200
opt.timeoutlen = 300
opt.clipboard = "unnamedplus"
