return {
    "nvim-treesitter/nvim-treesitter",
    opts = {
        indent = { enable = true },
        highlight = { enable = true },
        folds = { enable = true },
        ensure_installed = {
            "bash",
            "c",
            "diff",
            "html",
            "jsdoc",
            "json",
            "lua",
            "luadoc",
            "luap",
            "markdown",
            "markdown_inline",
            "printf",
            "python",
            "java",
            "query",
            "regex",
            "toml",
            "tsx",
            "typescript",
            "javascript",
            "vim",
            "vimdoc",
            "xml",
            "yaml",
        },
    },
}
